### ISSUE TITLE
Dependency directions

### ISSUE THREAD

**Issue by ChristinWhite** [collegboi/my-bitbar-plugins#1]
Hey Collegboi, I'm having trouble getting Gitty setup and I was hoping you might give a little direction for someone who isn't super familiar with Python.

I've installed Gitty from the BitBar site, I have Python installed on High Sierra via Homebrew with both Python and Pip pointing to Homebrew's Python, not the OS. 

I then installed GitPython via Pip but I still get the following error from BitBar:

```
Traceback (most recent call last):
File "/Users/cwhite/library/Mobile Documents/com~apple~CloudDocs/Application Sync/BitBar/Plugins/Enabled/git_python.5m.ph", line 12, in <module>
import git
ImportError: No module named git
```

I do also have Command Line Tools installed and Git is in my PATH if it's looking for that instead.

Any help would be awesome, it looks like a fantastic plugin!

**Comment by swifty-tim** [comment]
Hi,

“pip install git” will do the trick

Thank you

From Timothy

On 15 Dec 2017, 03:24 +0000, Chris White <notifications@github.com>, wrote:
> Hey Collegboi, I'm having trouble getting Gitty setup and I was hoping you might give a little direction for someone who isn't super familiar with Python.
> I've installed Gitty from the BitBar site, I have Python installed on High Sierra via Homebrew with both Python and Pip pointing to Homebrew's Python, not the OS.
> I then installed GitPython via Pip but I still get the following error from BitBar:
> Traceback (most recent call last):
> File "/Users/cwhite/library/Mobile Documents/com~apple~CloudDocs/Application Sync/BitBar/Plugins/Enabled/git_python.5m.ph", line 12, in <module>
> import git
> ImportError: No module named git
> I do also have Command Line Tools installed and Git is in my PATH if it's looking for that instead.
> Any help would be awesome, it looks like a fantastic plugin!
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.

-- 


This email originated from DIT. If you received this email in error, please 
delete it from your system. Please note that if you are not the named 
addressee, disclosing, copying, distributing or taking any action based on 
the contents of this email or attachments is prohibited. www.dit.ie

Is ó ITBÁC a tháinig an ríomhphost seo. Má fuair tú an ríomhphost seo trí 
earráid, scrios de do chóras é le do thoil. Tabhair ar aird, mura tú an 
seolaí ainmnithe, go bhfuil dianchosc ar aon nochtadh, aon chóipeáil, aon 
dáileadh nó ar aon ghníomh a dhéanfar bunaithe ar an ábhar atá sa 
ríomhphost nó sna hiatáin seo. www.dit.ie

Tá ITBÁC ag aistriú go Gráinseach Ghormáin – DIT is on the move to 
Grangegorman <http://www.dit.ie/grangegorman>

**Comment by mn113** [comment]
Hi, I have the same problem as above.

`pip install git` says `No matching distribution found for git`.
I did `pip install GitPython` successfully though, which seems to give me git.

From an interactive Python shell, I can now `import git` and test that it works with commands like `git.Repo(directory).branches`.
However the BitBar plugin still shows the above error.

I think it may be to do with the environment the BB script runs in being different in some way from my usual iTerm environment. I'm looking to maybe change the shebang or write a line to somehow pre-initialise the env this script runs in. Any ideas?

NB: I'm on Python 3.5.2

**Comment by mmorga** [comment]
Same problem as well. 

I get: `No matching distribution found for git`

for both Python 2.7.10 and 3.6.5.

do you have a link to the git library source page? Thanks!
